services:
  langflow:
    image: langflowai/langflow:1.3.4
    container_name: langflow_app
    command: >
      /bin/bash -c "
      echo 'Installing Python packages...' &&
      pip install --user gspread oauth2client &&
      echo 'Starting Langflow...' &&
      python -m langflow run --env-file /app/.env"
    ports:
      - "${LANGFLOW_PORT:-7860}:7860"
    env_file:
      - .env
    environment:
      - LANGFLOW_DATABASE_URL=${LANGFLOW_DATABASE_URL:-postgresql://langflow_user:password@db:5432/langflow_db}
      - LANGFLOW_COMPONENTS_PATH=${LANGFLOW_COMPONENTS_PATH:-/app/custom_components}
      - LANGFLOW_CONFIG_DIR=${LANGFLOW_CONFIG_DIR:-/app/langflow}
      - LANGFLOW_LOG_LEVEL=${LANGFLOW_LOG_LEVEL:-info}
      # Optional: Uncomment to use OpenAI components
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Optional: Uncomment for Redis cache
      # - LANGFLOW_CACHE_TYPE=${LANGFLOW_CACHE_TYPE}
      # - LANGFLOW_REDIS_URL=${LANGFLOW_REDIS_URL}
    volumes:
      - ./custom_components:/app/custom_components
      - ./data/langflow:/app/langflow
      - ./.env:/app/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: langflow_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-langflow_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-langflow_db}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  # Initialize volume permissions
  init-volumes:
    image: busybox
    command: sh -c "mkdir -p /app/langflow && chmod -R 777 /app/langflow"
    volumes:
      - ./data/langflow:/app/langflow
    restart: "no"

# No need for named volumes anymore since we're using local directories
# volumes:
#   langflow-data:
#   langflow-postgres: 